name: Deploy Flask App to Azure

on:
  push:
    branches:
      - master  # Spustí se pouze při pushi do master
    paths-ignore:
        - '**/*.md'  # Ignoruje všechny Markdown soubory ve všech složkách
  pull_request:
    branches-ignore:
      - master  # Pull requesty do master se ignorují

jobs:
  test:
    if: github.event_name == 'push'  # Spustí testy jen při pushi, ne při PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Set up virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate

      - name: Install dependencies
        run: |
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov

      - name: Verify installed packages
        run: |
          source antenv/bin/activate
          pip list | grep uvicorn || echo "Uvicorn není nainstalován!"
          which uvicorn || echo "Uvicorn není v PATH!"

      - name: Set environment variables
        run: |
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
          echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          source antenv/bin/activate
          pytest --cov --junitxml=junit.xml -o junit_family=legacy --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: junit.xml


  deploy:
    needs: test  # Deploy se spustí pouze, pokud testy projdou
    if: github.event_name == 'push'  # Spustí deploy jen při pushi, ne při PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Set up virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate

      - name: Install dependencies
        run: |
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installed packages
        run: |
          source antenv/bin/activate
          pip list | grep uvicorn || echo "Uvicorn není nainstalován!"
          which uvicorn || echo "Uvicorn není v PATH!"

      - name: Set environment variables
        run: |
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
          echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy environment variables to Azure
        run: |
          az webapp config appsettings set --name stin-zpravy --resource-group stin-zpravy_group \
          --settings NEWS_API_KEY=${{ secrets.NEWS_API_KEY }} \
                    OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}

      - name: Set startup command in Azure
        run: |
          az webapp config set --name stin-zpravy --resource-group stin-zpravy_group \
          --startup-file "python -m uvicorn flask_app.app:app --host 0.0.0.0 --port \$PORT --workers 1 --interface wsgi"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "stin-zpravy"
          package: .

      - name: Restart Azure App Service
        run: |
          az webapp restart --name stin-zpravy --resource-group stin-zpravy_group
