  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov

      - name: Set environment variables
        run: echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: pytest --cov=flask_app --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3  # Použití nejnovější verze
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Použití tokenu z GitHub Secrets
          files: ./coverage.xml
          fail_ci_if_error: true  # CI failne, pokud Codecov upload selže
          verbose: true  # Více informací v logu
