name: Deploy Flask App to Azure

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches-ignore:
      - master

jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov

      - name: Verify installed packages
        run: |
          source antenv/bin/activate
          pip list | grep uvicorn || echo "Uvicorn neni nainstalovan!"
          which uvicorn || echo "Uvicorn neni v PATH!"

      - name: Set environment variables for tests
        run: |
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
          echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          source antenv/bin/activate
          pytest --cov --junitxml=junit.xml -o junit_family=legacy --cov-report=xml

  deploy:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installed packages
        run: |
          source antenv/bin/activate
          pip list | grep uvicorn || echo "Uvicorn neni nainstalovan!"
          which uvicorn || echo "Uvicorn neni v PATH!"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FD445A6368E149B9B0780CDBC7B53B36 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E708DAC42D8484590A6B233EE771320 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42B716814DBB4A61A57916F8CB2498F7 }}

      - name: Set environment variables in Azure
        run: |
          az webapp config appsettings set --name stin-zpravy --resource-group stin-zpravy_group \
          --settings NEWS_API_KEY=${{ secrets.NEWS_API_KEY }} \
                    OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}

      - name: Set startup command for Flask app
        run: |
          az webapp config set --name stin-zpravy --resource-group stin-zpravy_group \
          --startup-file "python -m uvicorn flask_app.app:app --host 0.0.0.0 --port \$PORT --workers 1 --interface wsgi"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stin-zpravy'
          slot-name: 'Production'
          package: .
